"""initial schema and core tables

Revision ID: a5391192c53d
Revises: 
Create Date: 2026-05-05 03:04:38.656615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5391192c53d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # CREATE SCHEMAs (single source of truth)
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS mkt")
    op.execute("CREATE SCHEMA IF NOT EXISTS comercial")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funil_etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='comercial'
    )
    op.create_table('canais',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='core'
    )
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('pos_graduacao', 'curso_livre', 'congresso_online', 'congresso_presencial', 'comunidade', 'seminario_online', 'evento_online', name='tipo_produto', schema='core'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='core'
    )
    op.create_table('funil_resultado',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resultado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_funil_mes'),
    sa.ForeignKeyConstraint(['etapa_id'], ['comercial.funil_etapas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['core.produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'etapa_id', 'ano', 'mes'),
    schema='comercial'
    )
    op.create_table('reunioes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=255), nullable=True),
    sa.Column('aluno_email', sa.String(length=255), nullable=True),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('data_agendada', sa.Date(), nullable=False),
    sa.Column('data_realizada', sa.Date(), nullable=True),
    sa.Column('no_show', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resultou_em_venda', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['core.produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='comercial'
    )
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=255), nullable=False),
    sa.Column('aluno_email', sa.String(length=255), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prazo_recebimento_meses', sa.Integer(), nullable=True),
    sa.Column('a_vista', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['core.produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='comercial'
    )
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('meta_inscritos', sa.Integer(), nullable=True),
    sa.Column('meta_receita', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_inscricao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_cpl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orcamento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['core.produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('metricas_canal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canal_id', sa.UUID(), nullable=False),
    sa.Column('indicador', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('meta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('resultado', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('meta_extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_metricas_mes'),
    sa.CheckConstraint('semana BETWEEN 1 AND 5', name='ck_metricas_semana'),
    sa.ForeignKeyConstraint(['canal_id'], ['core.canais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['core.produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canal_id', 'indicador', 'produto_id', 'ano', 'mes', 'semana'),
    schema='mkt'
    )
    op.create_table('inscricoes_evento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('inscritos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('valor_inscricao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receita', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['core.eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'data_registro'),
    schema='mkt'
    )
    op.create_table('leads_eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('canal_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('inscritos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('investimento', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['core.canais.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['core.eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'canal_id', 'data'),
    schema='mkt'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads_eventos', schema='mkt')
    op.drop_table('inscricoes_evento', schema='mkt')
    op.drop_table('metricas_canal', schema='mkt')
    op.drop_table('eventos', schema='core')
    op.drop_table('vendas', schema='comercial')
    op.drop_table('reunioes', schema='comercial')
    op.drop_table('funil_resultado', schema='comercial')
    op.drop_table('users', schema='core')
    op.drop_table('produtos', schema='core')
    op.drop_table('canais', schema='core')
    op.drop_table('funil_etapas', schema='comercial')
    # ### end Alembic commands ###
